when@dev:
    monolog:
        handlers:
            main:
                type:  stream
                path:  '%kernel.logs_dir%/%kernel.environment%.log'
                level: debug
                channels: ['!event']
            console:
                type:   console
                process_psr_3_messages: false
                bubble: false
                verbosity_levels:
                    VERBOSITY_VERBOSE: INFO
                    VERBOSITY_VERY_VERBOSE: DEBUG
                channels: ["!event", "!doctrine", "!console"]
            console_debug:
                type:   console
                process_psr_3_messages: false
                bubble: false
                verbosity_levels:
                    VERBOSITY_VERBOSE: NOTICE
                    VERBOSITY_VERY_VERBOSE: NOTICE
                    VERBOSITY_DEBUG: DEBUG
                channels: ["doctrine", "event", "console"]

when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                buffer_size: 100 # How many messages should be saved? Prevent memory leaks
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                include_stacktraces: true

            deprecation_filter:
                type: filter
                handler: deprecation
                max_level: info
                channels: ["php"]
                process_psr_3_messages: false
            deprecation:
                type: stream
                path: "%kernel.logs_dir%/deprecations.log"
                include_stacktraces: true

            console_debug:
                type:   console
                process_psr_3_messages: false
                include_stacktraces: true
                verbosity_levels:
                    VERBOSITY_NORMAL: EMERGENCY
                    VERBOSITY_VERBOSE: INFO
                    VERBOSITY_VERY_VERBOSE: NOTICE
                    VERBOSITY_DEBUG: DEBUG
