sensio_framework_extra:
    router:
        annotations: false
    request:
        converters: false
        auto_convert: false
    cache:
        annotations: false
    view:
        annotations: false
    security:
        annotations: true
